interface=veth-ext-host
xdp_mode=generic
object_path=bpf/firewall.bpf.o
rules_path=rules.conf

syn_threshold=10000
udp_threshold=50000
icmp_threshold=10000
port_scan_threshold=100
connection_threshold=20000
window_ms=1000
ban_seconds=300
log_sample_rate=1

honeypot_enabled=true
honeypot_ifname=veth-honey-host
honeypot_ip=10.200.0.2
honeypot_mac=02:00:00:00:20:02
honeypot_port=22
honeypot_redirect_seconds=600
canary_ports=2222
